#!/usr/bin/env python3
import sys
from pathlib import Path

DATA_FILE = Path.home() / ".ana.json"
if not DATA_FILE.exists():
    DATA_FILE.write_text("{}")

if len(sys.argv) == 2:
    if sys.argv[1] == "greet":
        print("Hello, World!")